[project]
name = "dc-plus"
version = "0.1.0"
description = "A package that extends the functionality of dataclasses "
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
